# Оптимизация памяти под ноутбук Asus X540NA
org.gradle.jvmargs=-Xmx1280m -XX:+UseParallelGC -XX:MaxMetaspaceSize=384m
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.20.101-hotspot

# Быстрый инкрементальный кэш
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.daemon=true

# Оптимизация Kotlin: компиляция внутри процесса Gradle без спавна лишнего Kotlin Daemon (экономит ~500 МБ ОЗУ)
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process

# Современные флаги Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.overridePathCheck=true
