
org.gradle.jvmargs=-Xmx1280m -XX:+UseParallelGC -XX:MaxMetaspaceSize=384m

org.gradle.parallel=false
org.gradle.caching=true
org.gradle.daemon=true

kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process

android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.suppressUnsupportedCompileSdk=35
